### ISSUE TITLE
Chapter 21 - Meta Learners

### ISSUE THREAD

**Issue by jakubkaplan** [matheusfacure/python-causality-handbook#193]
There is an issue on chapter XXX, in the following paragraph
> Here, they plot the difference between the true causal effect (red outline) and the estimated causal effect, {tau} - {tau^hat}
, using an S-learner. The estimated causal effect is heavily downward biased. In other words, the true causal effect is frequently bigger than the estimated one.

It should be (changes highlighted in bold):
> Here, they plot the difference between the true causal effect (red outline) and the estimated causal effect, {tau} - {tau^hat}
, using an S-learner. The estimated causal effect is heavily **upward** biased. In other words, the true causal effect is frequently **smaller** than the estimated one.

This is based on the diagram and also looking at the figure description in the original paper, top of page 4: 
https://arxiv.org/abs/1608.00060

Let me know if I misunderstood, I spent some time thinking I must have it wrong, so it's perfectly possible, as I am a non-expert.

**Comment by matheusfacure** [comment]
The bias here is dowards because (tau-tau_hat>0). The distribution is for tau - tau_hat. That fact that it is mostly positive tells us that, most of the time tau > tau_hat, so our estimate tau_hat is smaller than it should be, hence, the downward bias. 
![image](https://user-images.githubusercontent.com/18542597/151770879-8f7a30ac-92fc-46f3-945a-b90cadad8817.png)

**Comment by jakubkaplan** [comment]
Got it, thank you for adding the clarification!
