### ISSUE TITLE
Chapter 03 - Correction when explaining ppf

### ISSUE THREAD

**Issue by Lucas-Okamura** [matheusfacure/python-causality-handbook#256]
There is an issue on chapter 03, in the following paragraphs "(...) saying that 50% of the mass of the standard normal distribution is below 0.0." and "(...) In other words, 0.05% of the mass falls above this value."

It should be "(...) saying that 50% of the mass of the standard normal distribution is below the sum between the mean and 0.0 times standard deviation." and "(...) In other words, 0.5% of the mass falls above this value.", respectively.

**Comment by donelianc** [comment]
I made PR #257 to add the second suggestion from @Lucas-Okamura's comment. 

I left the first suggestion to @matheusfacure since it looks like a wording issue. 

But agree with Lucas since the standard normal distribution doesn't imply that the distribution's mean is 0 (although it's pretty common to use a distribution with `mean=0` to facilitate calculations and examples maybe that's why Matheus wrote _"below 0.0"_), so his suggestion it's more accurate.
