### ISSUE TITLE
Placebo Variance Estimation accounting for time effect heterogeneity and staggered adoption

### ISSUE THREAD

**Issue by argideritzalpea** [matheusfacure/python-causality-handbook#323]
I propose an enhancement in [25-Synthetic-Diff-in-Diff.ipynb](https://github.com/matheusfacure/python-causality-handbook/blob/master/causal-inference-for-the-brave-and-true/25-Synthetic-Diff-in-Diff.ipynb):

The Placebo Variance Estimation section assumes the case in which there is only a single treatment period:
``` It turns out there are many solutions to this problem, but only one that fits the case for a single treated unit, which is the case we have here since only California was treated```

In the section immediately prior (Time Effect Heterogeneity and Staggered Adoption), the work had shown how to account for staggered adoption. I recommend that the Placebo Variance Estimation code be made more general to teach users how to apply variance estimation if there are multiple treatment periods with staggered adoption, as opposed to there only being a single treatment period.

**Comment by matheusfacure** [comment]
Estimating the variance for time series models is an active area of research. I'm not confident it can generalize. Do you have any resources that tell otherwise? I know Kaspar Wüthrich has two papers on the topic, one of which is covered in the apendix (conformal inference). From chatting with him, that is probably your best bet when you want flexibility in the counterfactual prediction.
